hidden_tags:
  type: list
  list_type: tag
  default: ''
  description:
    en: 'Select specific tags to hide in the layout'
hidden_tag_groups:
  type: list
  default: ''
  description:
    en: 'Enter the names of the tag groups you wish to hide in the layout.'
display_style:
  default: row
  type: enum
  choices:
    - row
    - column
  description:
    en: 'Select how you would like tags to appear. (Row for one after another, column for one on each line)'
show_count:
  default: false
  type: bool
  description:
    en: 'Show the count beside each tag.'
sort_type:
  default: 'Count Descending'
  type: enum
  choices:
    - 'Count Ascending'
    - 'Count Descending'
    - 'Alphabetical Ascending'
    - 'Alphabetical Descending'
  description:
    en: 'Select the manner in which tags should be sorted'
tag_groups_default_expanded:
  default: true
  type: bool
  description:
    en: 'Check to make tag groups expanded by default'
